### ISSUE TITLE
Error when player join map

### ISSUE THREAD

**Issue by sdvn** [TigerHix/Mine-Fortress#11]
[15:19:36] [Server thread/INFO]: SidSchoenewerk[/127.0.0.1:38434] logged in with entity id 1103 at ([Matdaibang]-909.5, 4.0, 908.4)
[15:19:42] [Server thread/WARN]: java.lang.ClassCastException: me.tigerhix.framework.game.player.Gamer cannot be cast to org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer
[15:19:42] [Server thread/WARN]:    at me.tigerhix.framework.commons.lib.attributestorage.AttributeHider$1.onPacketSending(AttributeHider.java:65)
[15:19:42] [Server thread/WARN]:    at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[15:19:42] [Server thread/WARN]:    at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[15:19:42] [Server thread/WARN]:    at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:638)
[15:19:42] [Server thread/WARN]:    at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:614)
[15:19:42] [Server thread/WARN]:    at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:312)
[15:19:42] [Server thread/WARN]:    at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278)
[15:19:42] [Server thread/WARN]:    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:417)
[15:19:42] [Server thread/WARN]:    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84)
[15:19:42] [Server thread/WARN]:    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:383)
[15:19:42] [Server thread/WARN]:    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:351)
[15:19:42] [Server thread/WARN]:    at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127)
[15:19:42] [Server thread/WARN]:    at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.EntityPlayer.openTrade(EntityPlayer.java:720)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.EntityVillager.a(EntityVillager.java:136)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.EntityInsentient.e(EntityInsentient.java:811)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.EntityHuman.u(EntityHuman.java:913)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1333)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:19:42] [Server thread/WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:19:42] [Server thread/WARN]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[15:19:42] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[15:19:42] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)

**Comment by TigerHix** [comment]
It seems like Mine Fortress messed up with NBTs.

I have sent you a hotfix via forum PM. Let me know whether it is working or not. :)
